framework:
    messenger:
        failure_transport: failed

        transports:
            # https://symfony.com/doc/current/messenger.html#transport-configuration
            async:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    use_notify: true
                    check_delayed_interval: 60000
                retry_strategy:
                    max_retries: 3
                    multiplier: 2
            failed: 'doctrine://default?queue_name=failed'
            # sync: 'sync://'
            kafka:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    metadata.broker.list: '%env(KAFKA_BROKERS)%'
                    security.protocol: 'plaintext'
                    allow.auto.create.topics: true
                    message.send.max.retries: 5
                    auto.offset.reset: 'earliest'
                    producer_topic: 'first_topic'
                    group.id: 'first-consumer-group'
                    consumer_topics:
                        - 'first_topic'

        routing:
            App\Messenger\Message\TryMessage: kafka

        serializer:
            default_serializer: messenger.transport.symfony_serializer

# when@test:
#    framework:
#        messenger:
#            transports:
#                # replace with your transport name here (e.g., my_transport: 'in-memory://')
#                # For more Messenger testing tools, see https://github.com/zenstruck/messenger-test
#                async: 'in-memory://'
